/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedConciergeRouteImport } from './routes/_authenticated/concierge'
import { Route as AuthenticatedFinancialsRouteImport } from './routes/_authenticated/financials'
import { Route as AuthenticatedGuestsRouteImport } from './routes/_authenticated/guests'
import { Route as AuthenticatedHotelsRouteImport } from './routes/_authenticated/hotels'
import { Route as AuthenticatedHousekeepingRouteImport } from './routes/_authenticated/housekeeping'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedBookingsBookingIdRouteImport } from './routes/_authenticated/bookings.$bookingId'
import { Route as AuthenticatedBookingsNewRouteImport } from './routes/_authenticated/bookings.new'
import { Route as AuthenticatedGuestsGuestIdRouteImport } from './routes/_authenticated/guests.$guestId'
import { Route as AuthenticatedHotelsHotelIdRouteImport } from './routes/_authenticated/hotels.$hotelId'
import { Route as AuthenticatedHotelsNewRouteImport } from './routes/_authenticated/hotels.new'
import { Route as AuthenticatedRoomsRoomIdRouteImport } from './routes/_authenticated/rooms.$roomId'
import { Route as AuthenticatedRoomsNewRouteImport } from './routes/_authenticated/rooms.new'
import { Route as AuthenticatedHotelsHotelIdEditRouteImport } from './routes/_authenticated/hotels.$hotelId.edit'
import { Route as AuthenticatedRoomsRoomIdEditRouteImport } from './routes/_authenticated/rooms.$roomId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConciergeRoute = AuthenticatedConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancialsRoute = AuthenticatedFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuestsRoute = AuthenticatedGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHotelsRoute = AuthenticatedHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHousekeepingRoute =
  AuthenticatedHousekeepingRouteImport.update({
    id: '/housekeeping',
    path: '/housekeeping',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingsBookingIdRoute =
  AuthenticatedBookingsBookingIdRouteImport.update({
    id: '/$bookingId',
    path: '/$bookingId',
    getParentRoute: () => AuthenticatedBookingsRoute,
  } as any)
const AuthenticatedBookingsNewRoute =
  AuthenticatedBookingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedBookingsRoute,
  } as any)
const AuthenticatedGuestsGuestIdRoute =
  AuthenticatedGuestsGuestIdRouteImport.update({
    id: '/$guestId',
    path: '/$guestId',
    getParentRoute: () => AuthenticatedGuestsRoute,
  } as any)
const AuthenticatedHotelsHotelIdRoute =
  AuthenticatedHotelsHotelIdRouteImport.update({
    id: '/$hotelId',
    path: '/$hotelId',
    getParentRoute: () => AuthenticatedHotelsRoute,
  } as any)
const AuthenticatedHotelsNewRoute = AuthenticatedHotelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedHotelsRoute,
} as any)
const AuthenticatedRoomsRoomIdRoute =
  AuthenticatedRoomsRoomIdRouteImport.update({
    id: '/$roomId',
    path: '/$roomId',
    getParentRoute: () => AuthenticatedRoomsRoute,
  } as any)
const AuthenticatedRoomsNewRoute = AuthenticatedRoomsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoomsRoute,
} as any)
const AuthenticatedHotelsHotelIdEditRoute =
  AuthenticatedHotelsHotelIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedHotelsHotelIdRoute,
  } as any)
const AuthenticatedRoomsRoomIdEditRoute =
  AuthenticatedRoomsRoomIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedRoomsRoomIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/concierge': typeof AuthenticatedConciergeRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/guests': typeof AuthenticatedGuestsRouteWithChildren
  '/hotels': typeof AuthenticatedHotelsRouteWithChildren
  '/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/rooms': typeof AuthenticatedRoomsRouteWithChildren
  '/staff': typeof AuthenticatedStaffRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/guests/$guestId': typeof AuthenticatedGuestsGuestIdRoute
  '/hotels/$hotelId': typeof AuthenticatedHotelsHotelIdRouteWithChildren
  '/hotels/new': typeof AuthenticatedHotelsNewRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRouteWithChildren
  '/rooms/new': typeof AuthenticatedRoomsNewRoute
  '/hotels/$hotelId/edit': typeof AuthenticatedHotelsHotelIdEditRoute
  '/rooms/$roomId/edit': typeof AuthenticatedRoomsRoomIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/concierge': typeof AuthenticatedConciergeRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/guests': typeof AuthenticatedGuestsRouteWithChildren
  '/hotels': typeof AuthenticatedHotelsRouteWithChildren
  '/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/rooms': typeof AuthenticatedRoomsRouteWithChildren
  '/staff': typeof AuthenticatedStaffRoute
  '/': typeof AuthenticatedIndexRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/guests/$guestId': typeof AuthenticatedGuestsGuestIdRoute
  '/hotels/$hotelId': typeof AuthenticatedHotelsHotelIdRouteWithChildren
  '/hotels/new': typeof AuthenticatedHotelsNewRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRouteWithChildren
  '/rooms/new': typeof AuthenticatedRoomsNewRoute
  '/hotels/$hotelId/edit': typeof AuthenticatedHotelsHotelIdEditRoute
  '/rooms/$roomId/edit': typeof AuthenticatedRoomsRoomIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/concierge': typeof AuthenticatedConciergeRoute
  '/_authenticated/financials': typeof AuthenticatedFinancialsRoute
  '/_authenticated/guests': typeof AuthenticatedGuestsRouteWithChildren
  '/_authenticated/hotels': typeof AuthenticatedHotelsRouteWithChildren
  '/_authenticated/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/_authenticated/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/_authenticated/guests/$guestId': typeof AuthenticatedGuestsGuestIdRoute
  '/_authenticated/hotels/$hotelId': typeof AuthenticatedHotelsHotelIdRouteWithChildren
  '/_authenticated/hotels/new': typeof AuthenticatedHotelsNewRoute
  '/_authenticated/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRouteWithChildren
  '/_authenticated/rooms/new': typeof AuthenticatedRoomsNewRoute
  '/_authenticated/hotels/$hotelId/edit': typeof AuthenticatedHotelsHotelIdEditRoute
  '/_authenticated/rooms/$roomId/edit': typeof AuthenticatedRoomsRoomIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bookings'
    | '/calendar'
    | '/concierge'
    | '/financials'
    | '/guests'
    | '/hotels'
    | '/housekeeping'
    | '/inventory'
    | '/messages'
    | '/payments'
    | '/reviews'
    | '/rooms'
    | '/staff'
    | '/bookings/$bookingId'
    | '/bookings/new'
    | '/guests/$guestId'
    | '/hotels/$hotelId'
    | '/hotels/new'
    | '/rooms/$roomId'
    | '/rooms/new'
    | '/hotels/$hotelId/edit'
    | '/rooms/$roomId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bookings'
    | '/calendar'
    | '/concierge'
    | '/financials'
    | '/guests'
    | '/hotels'
    | '/housekeeping'
    | '/inventory'
    | '/messages'
    | '/payments'
    | '/reviews'
    | '/rooms'
    | '/staff'
    | '/'
    | '/bookings/$bookingId'
    | '/bookings/new'
    | '/guests/$guestId'
    | '/hotels/$hotelId'
    | '/hotels/new'
    | '/rooms/$roomId'
    | '/rooms/new'
    | '/hotels/$hotelId/edit'
    | '/rooms/$roomId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/bookings'
    | '/_authenticated/calendar'
    | '/_authenticated/concierge'
    | '/_authenticated/financials'
    | '/_authenticated/guests'
    | '/_authenticated/hotels'
    | '/_authenticated/housekeeping'
    | '/_authenticated/inventory'
    | '/_authenticated/messages'
    | '/_authenticated/payments'
    | '/_authenticated/reviews'
    | '/_authenticated/rooms'
    | '/_authenticated/staff'
    | '/_authenticated/'
    | '/_authenticated/bookings/$bookingId'
    | '/_authenticated/bookings/new'
    | '/_authenticated/guests/$guestId'
    | '/_authenticated/hotels/$hotelId'
    | '/_authenticated/hotels/new'
    | '/_authenticated/rooms/$roomId'
    | '/_authenticated/rooms/new'
    | '/_authenticated/hotels/$hotelId/edit'
    | '/_authenticated/rooms/$roomId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/concierge': {
      id: '/_authenticated/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof AuthenticatedConciergeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials': {
      id: '/_authenticated/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof AuthenticatedFinancialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guests': {
      id: '/_authenticated/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AuthenticatedGuestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hotels': {
      id: '/_authenticated/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof AuthenticatedHotelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/housekeeping': {
      id: '/_authenticated/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof AuthenticatedHousekeepingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings/$bookingId': {
      id: '/_authenticated/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof AuthenticatedBookingsBookingIdRouteImport
      parentRoute: typeof AuthenticatedBookingsRoute
    }
    '/_authenticated/bookings/new': {
      id: '/_authenticated/bookings/new'
      path: '/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof AuthenticatedBookingsNewRouteImport
      parentRoute: typeof AuthenticatedBookingsRoute
    }
    '/_authenticated/guests/$guestId': {
      id: '/_authenticated/guests/$guestId'
      path: '/$guestId'
      fullPath: '/guests/$guestId'
      preLoaderRoute: typeof AuthenticatedGuestsGuestIdRouteImport
      parentRoute: typeof AuthenticatedGuestsRoute
    }
    '/_authenticated/hotels/$hotelId': {
      id: '/_authenticated/hotels/$hotelId'
      path: '/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof AuthenticatedHotelsHotelIdRouteImport
      parentRoute: typeof AuthenticatedHotelsRoute
    }
    '/_authenticated/hotels/new': {
      id: '/_authenticated/hotels/new'
      path: '/new'
      fullPath: '/hotels/new'
      preLoaderRoute: typeof AuthenticatedHotelsNewRouteImport
      parentRoute: typeof AuthenticatedHotelsRoute
    }
    '/_authenticated/rooms/$roomId': {
      id: '/_authenticated/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdRouteImport
      parentRoute: typeof AuthenticatedRoomsRoute
    }
    '/_authenticated/rooms/new': {
      id: '/_authenticated/rooms/new'
      path: '/new'
      fullPath: '/rooms/new'
      preLoaderRoute: typeof AuthenticatedRoomsNewRouteImport
      parentRoute: typeof AuthenticatedRoomsRoute
    }
    '/_authenticated/hotels/$hotelId/edit': {
      id: '/_authenticated/hotels/$hotelId/edit'
      path: '/edit'
      fullPath: '/hotels/$hotelId/edit'
      preLoaderRoute: typeof AuthenticatedHotelsHotelIdEditRouteImport
      parentRoute: typeof AuthenticatedHotelsHotelIdRoute
    }
    '/_authenticated/rooms/$roomId/edit': {
      id: '/_authenticated/rooms/$roomId/edit'
      path: '/edit'
      fullPath: '/rooms/$roomId/edit'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdEditRouteImport
      parentRoute: typeof AuthenticatedRoomsRoomIdRoute
    }
  }
}

interface AuthenticatedBookingsRouteChildren {
  AuthenticatedBookingsBookingIdRoute: typeof AuthenticatedBookingsBookingIdRoute
  AuthenticatedBookingsNewRoute: typeof AuthenticatedBookingsNewRoute
}

const AuthenticatedBookingsRouteChildren: AuthenticatedBookingsRouteChildren = {
  AuthenticatedBookingsBookingIdRoute: AuthenticatedBookingsBookingIdRoute,
  AuthenticatedBookingsNewRoute: AuthenticatedBookingsNewRoute,
}

const AuthenticatedBookingsRouteWithChildren =
  AuthenticatedBookingsRoute._addFileChildren(
    AuthenticatedBookingsRouteChildren,
  )

interface AuthenticatedGuestsRouteChildren {
  AuthenticatedGuestsGuestIdRoute: typeof AuthenticatedGuestsGuestIdRoute
}

const AuthenticatedGuestsRouteChildren: AuthenticatedGuestsRouteChildren = {
  AuthenticatedGuestsGuestIdRoute: AuthenticatedGuestsGuestIdRoute,
}

const AuthenticatedGuestsRouteWithChildren =
  AuthenticatedGuestsRoute._addFileChildren(AuthenticatedGuestsRouteChildren)

interface AuthenticatedHotelsHotelIdRouteChildren {
  AuthenticatedHotelsHotelIdEditRoute: typeof AuthenticatedHotelsHotelIdEditRoute
}

const AuthenticatedHotelsHotelIdRouteChildren: AuthenticatedHotelsHotelIdRouteChildren =
  {
    AuthenticatedHotelsHotelIdEditRoute: AuthenticatedHotelsHotelIdEditRoute,
  }

const AuthenticatedHotelsHotelIdRouteWithChildren =
  AuthenticatedHotelsHotelIdRoute._addFileChildren(
    AuthenticatedHotelsHotelIdRouteChildren,
  )

interface AuthenticatedHotelsRouteChildren {
  AuthenticatedHotelsHotelIdRoute: typeof AuthenticatedHotelsHotelIdRouteWithChildren
  AuthenticatedHotelsNewRoute: typeof AuthenticatedHotelsNewRoute
}

const AuthenticatedHotelsRouteChildren: AuthenticatedHotelsRouteChildren = {
  AuthenticatedHotelsHotelIdRoute: AuthenticatedHotelsHotelIdRouteWithChildren,
  AuthenticatedHotelsNewRoute: AuthenticatedHotelsNewRoute,
}

const AuthenticatedHotelsRouteWithChildren =
  AuthenticatedHotelsRoute._addFileChildren(AuthenticatedHotelsRouteChildren)

interface AuthenticatedRoomsRoomIdRouteChildren {
  AuthenticatedRoomsRoomIdEditRoute: typeof AuthenticatedRoomsRoomIdEditRoute
}

const AuthenticatedRoomsRoomIdRouteChildren: AuthenticatedRoomsRoomIdRouteChildren =
  {
    AuthenticatedRoomsRoomIdEditRoute: AuthenticatedRoomsRoomIdEditRoute,
  }

const AuthenticatedRoomsRoomIdRouteWithChildren =
  AuthenticatedRoomsRoomIdRoute._addFileChildren(
    AuthenticatedRoomsRoomIdRouteChildren,
  )

interface AuthenticatedRoomsRouteChildren {
  AuthenticatedRoomsRoomIdRoute: typeof AuthenticatedRoomsRoomIdRouteWithChildren
  AuthenticatedRoomsNewRoute: typeof AuthenticatedRoomsNewRoute
}

const AuthenticatedRoomsRouteChildren: AuthenticatedRoomsRouteChildren = {
  AuthenticatedRoomsRoomIdRoute: AuthenticatedRoomsRoomIdRouteWithChildren,
  AuthenticatedRoomsNewRoute: AuthenticatedRoomsNewRoute,
}

const AuthenticatedRoomsRouteWithChildren =
  AuthenticatedRoomsRoute._addFileChildren(AuthenticatedRoomsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRouteWithChildren
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedConciergeRoute: typeof AuthenticatedConciergeRoute
  AuthenticatedFinancialsRoute: typeof AuthenticatedFinancialsRoute
  AuthenticatedGuestsRoute: typeof AuthenticatedGuestsRouteWithChildren
  AuthenticatedHotelsRoute: typeof AuthenticatedHotelsRouteWithChildren
  AuthenticatedHousekeepingRoute: typeof AuthenticatedHousekeepingRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRouteWithChildren
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRouteWithChildren,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedConciergeRoute: AuthenticatedConciergeRoute,
  AuthenticatedFinancialsRoute: AuthenticatedFinancialsRoute,
  AuthenticatedGuestsRoute: AuthenticatedGuestsRouteWithChildren,
  AuthenticatedHotelsRoute: AuthenticatedHotelsRouteWithChildren,
  AuthenticatedHousekeepingRoute: AuthenticatedHousekeepingRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRouteWithChildren,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
